<option value="<?php if(isset($_POST['website_type'])) echo htmlentities($_POST['website_type']); ?>"></option>
<option value="Construction">Construction</option>
<option value="e-commerce">e-commerce</option>
<option value="Entertainment and media">Entertainment and media</option>
<option value="Travel and tour">Travel and tour</option>
<option value="Hotel and Accomodation">Hotel and Accomodation tour</option>
<option value="Food retail and services">Food retail and services</option>
<option value="Community and society">Community and society</option>
<option value="Colleges and universities">Colleges and universities</option>
<option value="Writers and authors">Writers and authors</option>
<option value="Inforamtion and communication">Inforamtion and communication</option>
<option value="Automotive">Automotive</option>
<option value="Education">Education</option>
<option value="Personal care and services">Personal care and services</option>
<option value="Logistics and transportation">Logistics and transportation</option>
<option value="Computers and electronics">Computers and electronics</option>
<option value="Sports and training">Sports and training</option>